/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

  // you can add a icon to a html canvas. simply supply its element id and the weather you want to show.
  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start all icons animation!
  skycons.play();

  // update a icon on  canvas by its id
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
/*
Get value from Bootstrap dropdown menu
*/

//選單旁邊加溫度
$(" li a ").each(function(index,element){
  //console.log($(element).text());
  $.getJSON(getAPI($(element).text()),function(data){
    var temp = tempFtoC(data.query.results.channel.item.condition.temp);
    $("<span>").text(temp + "°C").css({"float" : "right"}).appendTo($(element));
  })
})


$('#dropdown li a').on('click', function(e){
    //alert($(this).text());
    $("#city").text($(this).text());
    var text = $(e.target).text();
    console.log(text);
    text=text.slice(0,3); //讀前面三個字
    console.log(text)
    $.getJSON(getAPI(text),function(data){
  //console.log (data) ;
  var temp = tempFtoC(data.query.results.channel.item.condition.temp);
  var low1 = tempFtoC(data.query.results.channel.item.forecast[1].low);
  var high1 = tempFtoC(data.query.results.channel.item.forecast[1].high);
  var low2 = tempFtoC(data.query.results.channel.item.forecast[2].low);
  var high2 = tempFtoC(data.query.results.channel.item.forecast[2].high);
  var low3 = tempFtoC(data.query.results.channel.item.forecast[3].low);
  var high3 = tempFtoC(data.query.results.channel.item.forecast[3].high);
      $(".temperature").text(temp);
      //console.log(temp);
      $(".date").text(data.query.results.channel.item.forecast[0].date + " : ");
      $(".textCondition").text(data.query.results.channel.item.condition.text);
      $("#forcast1").text(data.query.results.channel.item.forecast[1].date );
      $("#forcast2").text(data.query.results.channel.item.forecast[2].date );
      $("#forcast3").text(data.query.results.channel.item.forecast[3].date );
      $("#highToLow1").text(low1 + "-" + high1 + "℃");
      $("#highToLow2").text(low2 + "-" + high2 + "℃");
      $("#highToLow3").text(low3 + "-" + high3 + "℃");
      skycons.set("today", getIcon(data.query.results.channel.item.condition.text));
      skycons.set("day1", getIcon(data.query.results.channel.item.forecast[1].text));
      skycons.set("day2", getIcon(data.query.results.channel.item.forecast[2].text));
      skycons.set("day3", getIcon(data.query.results.channel.item.forecast[3].text));
})   
});



//網頁一開始進去就是台北市
$(document).ready(function () {
   $.getJSON("https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taipei%20City%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys",
   function(data){
  //console.log (data) ;
  var temp = tempFtoC(data.query.results.channel.item.condition.temp);
  var low1 = tempFtoC(data.query.results.channel.item.forecast[1].low);
  var high1 = tempFtoC(data.query.results.channel.item.forecast[1].high);
  var low2 = tempFtoC(data.query.results.channel.item.forecast[2].low);
  var high2 = tempFtoC(data.query.results.channel.item.forecast[2].high);
  var low3 = tempFtoC(data.query.results.channel.item.forecast[3].low);
  var high3 = tempFtoC(data.query.results.channel.item.forecast[3].high);
      $(".temperature").text(temp);
      //console.log(temp);
      $(".date").text(data.query.results.channel.item.forecast[0].date + " : ");
      $(".textCondition").text(data.query.results.channel.item.condition.text);
      $("#forcast1").text(data.query.results.channel.item.forecast[1].date );
      $("#forcast2").text(data.query.results.channel.item.forecast[2].date );
      $("#forcast3").text(data.query.results.channel.item.forecast[3].date );
      $("#highToLow1").text(low1 + "-" + high1 + "℃");
      $("#highToLow2").text(low2 + "-" + high2 + "℃");
      $("#highToLow3").text(low3 + "-" + high3 + "℃");
      skycons.set("today", getIcon(data.query.results.channel.item.condition.text));
      skycons.set("day1", getIcon(data.query.results.channel.item.forecast[1].text));
      skycons.set("day2", getIcon(data.query.results.channel.item.forecast[2].text));
      skycons.set("day3", getIcon(data.query.results.channel.item.forecast[3].text));
})   
})


function getAPI(text){
    switch (text) {
      case "台北市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taipei%20City%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "新北市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22New%20Taipei%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "台中市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taichung%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "臺南市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Tainan%20City%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "高雄市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Kaohsiung%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "基隆市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Keelung%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "桃園市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taoyuan%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "新竹市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Hsinchu%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "新竹縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Hsinchu%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "苗栗縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Miaoli%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "彰化縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Changhua%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "南投縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Nantou%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "雲林縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Dounan%20Township%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "嘉義市":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Chiayi%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "嘉義縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Chiayi%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "屏東縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Pingtung%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "宜蘭縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Ilan%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "花蓮縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Hualien%20City%20Taiwan%20%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "台東縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Taitung%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "澎湖縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Makung%20City%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "金門縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Lieyu%20Township%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
      case "連江縣":
          return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22Juguang%20Township%20Taiwan%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
    }
  }

function tempFtoC(F) {
    return Math.round((F - 32) * (5 / 9)).toString();
}


function getIcon(text) {
    switch (text) {
        case "Sunny":
            return "CLEAR_DAY";
        case "Clear (night)":
            return "CLEAR_NIGHT";
        case "Partly Cloudy":
            return "PARTLY_CLOUDY_DAY";
        case "Cloudy":
            return "CLOUDY";
        case "Mostly Cloudy":
            return "CLOUDY";
        case "Rain":
            return "RAIN";
        case "Scattered Showers":
            return "RAIN";
        case "Showers":
            return "RAIN";
        case "Scattered Thunderstorms":
            return "RAIN";
        case "Thunderstorms":
            return "RAIN";
        case "Sleet":
            return "SLEET";
        case "Snow":
            return "SNOW";
        case "Windy":
            return "WIND";
        case "Breezy":
            return "WIND";
        case "Foggy":
            return "FOG";
    }
}